using System;
using System.Collections.Generic;
using System.Text;

namespace PI2_XamarinForms.Factory
{
    public class FA_CountryPicker : FactoryPicker
    {
        protected override List<dynamic> CreateBody()
        {
            return new List<dynamic>{
                "Albania",
                "Antigua",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Bosnia and Herzegovina",
                "Brazil",
                "Bulgaria",
                "Cabo Verde",
                "Canada",
                "Chile",
                "Colombia",
                "Costa Rica",
                "Croatia",
                "Cuba",
                "Cyprus",
                "Czech",
                "Denmark",
                "Dominica",
                "Ecuador",
                "El Salvador",
                "Estonia",
                "Fiji",
                "Finland",
                "France",
                "Georgia",
                "Germany",
                "Greece",
                "Grenada",
                "Guatemala",
                "Guyana",
                "Hungary",
                "Iceland",
                "Ireland",
                "Israel",
                "Italy",
                "Jamaica",
                "Japan",
                "Kazakhstan",
                "Kiribati",
                "Kuwait",
                "Kyrgyzstan",
                "Latvia",
                "Lithuania",
                "Luxembourg",
                "Macau",
                "Maldives",
                "Malta",
                "Mauritius",
                "Mexico",
                "Mongolia",
                "Montenegro",
                "Netherlands",
                "New Zealand",
                "Nicaragua",
                "Norway",
                "Oman",
                "Panama",
                "Paraguay",
                "Philippines",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Republic of Korea",
                "Romania",
                "Russian Federation",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Vincent and Grenadines",
                "San Marino",
                "Serbia",
                "Seychelles",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "South Africa",
                "Spain",
                "Sri Lanka",
                "Suriname",
                "Sweden",
                "Switzerland",
                "Thailand",
                "Trinidad and Tobago",
                "Turkey",
                "Turkmenistan",
                "Ukraine",
                "United Arab Emirates",
                "United Kingdom",
                "United States",
                "Uruguay",
                "Uzbekistan"
            };
        }

        protected override string GetTitle()
        {
            return "Choose your country";
        }
    }
}
